on:
  push:
  pull_request_target:
    branches:
      - main
jobs:
  move-code:z
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: olivr/copybara-action@v1.2.2
        with:
          ssh_key: ${{ secrets.GH_SSH_BOT }}
          access_token: ${{ secrets.GH_TOKEN_BOT }}
          sot_repo: adarshaacharya/nx-copybara
          destination_repo: adarshaacharya/copybara-destination
          push_include: '.github/workflows/build-pr.yml .github/workflows/move-code.yml apps/blog*/** libs/** externals/blog/** tools/** .*rc .*ignore *.json *.js *.lock'
          push_exclude: 'nx.json tsconfig.base.json workspace.json'
          pr_move: |
            nx.json||externals/blog/nx.json
            tsconfig.base.json||externals/blog/tsconfig.base.json
            workspace.json||externals/blog/workspace.json
